config = {'train_data_path':['data/raw_files/subset0/',
                             'data/raw_files/subset1/',
                             'data/raw_files/subset2/',
                             'data/raw_files/subset3/',
                             'data/raw_files/subset4/',
                             'data/raw_files/subset5/',
                             'data/raw_files/subset6/',
                             'data/raw_files/subset7/',
                             'data/raw_files/subset8/'],
          'val_data_path':['data/raw_files/subset9/'], 
          'test_data_path':['data/raw_files/subset9/'], 
          
          'train_preprocess_result_path':'data/preprocessed/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'data/preprocessed/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'data/preprocessed/',
          
          'train_annos_path':'data/annotations.csv',
          'val_annos_path':'data/annotations.csv',
          'test_annos_path':'data/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',

          'luna_segment':'data/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'data/preprocessed/',
          'luna_data':'data/raw_files/',
          'luna_label':'data/annotations.csv'
         } 
