config = {
          # 'train_preprocess_result_path':'/home/cougarnet.uh.edu/pyuan2/Projects/Incidental_Lung/Detector_data/', # contains numpy for the data and label, which is generated by prepare.py
          # 'val_preprocess_result_path':'/home/cougarnet.uh.edu/pyuan2/Projects/Incidental_Lung/Detector_data/',  # make sure copy all the numpy into one folder after prepare.py
          # 'test_preprocess_result_path':'/home/cougarnet.uh.edu/pyuan2/Projects/Incidental_Lung/Detector_data/',

          # 'train_preprocess_result_path': '/home/cougarnet.uh.edu/pyuan2/Projects/DeepLung-3D_Lung_Nodule_Detection/data/raw_files/',
          # 'val_preprocess_result_path': '/home/cougarnet.uh.edu/pyuan2/Projects/DeepLung-3D_Lung_Nodule_Detection/data/raw_files/',
          # 'test_preprocess_result_path':'/home/cougarnet.uh.edu/pyuan2/Projects/DeepLung-3D_Lung_Nodule_Detection/data/raw_files/',

          'data_root_path': '/home/cougarnet.uh.edu/pyuan2/Projects/Incidental_Lung/data/',
          'train_data_path':[],
          'val_data_path':[],
          'test_data_path':[],

          # 'train_preprocess_result_path': '/home/cougarnet.uh.edu/pyuan2/Projects/DeepLung-3D_Lung_Nodule_Detection/data/preprocessed/',
          # 'val_preprocess_result_path': '/home/cougarnet.uh.edu/pyuan2/Projects/DeepLung-3D_Lung_Nodule_Detection/data/preprocessed/',
          # 'test_preprocess_result_path': '/home/cougarnet.uh.edu/pyuan2/Projects/DeepLung-3D_Lung_Nodule_Detection/data/preprocessed/',

          'black_list':[],
          
          'preprocessing_backend':'python',
          }

         #  'luna_segmentgment':'/home/cougarnet.uh.edu/mpadmana/Downloads/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
         #  'preprocess_result_path':'/home/cougarnet.uh.edu/mpadmana/DeepLung_original/prepared/',
         #  'luna_data':'/home/cougarnet.uh.edu/mpadmana/Desktop/raw_files/',
         #  'luna_label':'/home/cougarnet.uh.edu/mpadmana/DeepLung_original/evaluationScript/annotations/annotations.csv'
         # }
